config/routes.rb
Rails.application.routes.draw do

  get '/:room_hash' => 'chats#room', :as => :chat

  get 'chats/room'

  get 'session/new'

  get 'session/create'

  resources :messages
  resources :dialogs

  root 'sessions#new'

  post '/login' => 'sessions#create', :as => :login

  get  '/chatroom/:room_hash' => 'chats#room', :as => :chat_old
  get  '/:room_hash/admin' => 'chats#admin', :as => :admin_room
  post  '/room_admin' => 'chats#update_room'
  post  '/change_name' => 'sessions#change_name', :as => :change_name
  get  '/my_rooms' => 'chats#index', :as => :chat_index

  get 'approve/:room_id/:user_id' => 'chats#approve', :as => :approve
  get 'get_out/:room_id/:user_id' => 'chats#get_out', :as => :get_out

end

app/models/message.rb
class Message < ActiveRecord::Base

  belongs_to :user, foreign_key: :sender_id
  belongs_to :chat, foreign_key: :room_id

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    if params[:message][:body].blank?
      render js: "поле не может быть пустым"
    else
      @message = Message.new(message_params)
      user = User.find(session[:user_id])
      chat = Chat.find_by_title(params[:some_data])
      if chat.user.id == session[:user_id] or (chat.whitelists.find_by_user_id(user.id) and chat.whitelists.find_by_user_id(user.id).approve)
        @message.room_id = chat.id    #TODO сделать валидацию. ЗАЩИТА!!
        @chat = Chat.find(@message.room_id)
        @message.sender_id = session[:user_id]
        @message.save
      end
    end


    # respond_to do |format|
    #   if @message.save
    #     format.html { redirect_to @message, notice: 'Message was successfully created.' }
    #     format.json { render :show, status: :created, location: @message }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @message.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:from_id, :to_id, :body)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :from_id %><br>
    <%= f.number_field :from_id %>
  </div>
  <div class="field">
    <%= f.label :to_id %><br>
    <%= f.number_field :to_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/_message.erb
<div class="message">
  <div class="name"><%= (@message.user.username.blank?)? @chat.whitelists.find_by_user_id(@message.user.id).salt : @message.user.username %></div>
  <div class="text">
    <%= @message.body %>
  </div>
</div>

app/views/messages/create.js.erb
<% publish_to "/messages/new/#{@chat.title}" do %>
$('.content').append('<%= j render 'message'%>');
$("html, body").animate({ scrollTop: $(document).height() }, "slow");

    $.ionSound.play(sound);

<% end %>
$('#new_message')[0].reset();

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <thead>
    <tr>
      <th>From</th>
      <th>To</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.from_id %></td>
        <td><%= message.to_id %></td>
        <td><%= message.content %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= form_for Message.new, remote: true do |f| %>
    <%= f.text_field :content %>
    <%= f.submit "Send" %>
<% end %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From:</strong>
  <%= @message.from_id %>
</p>

<p>
  <strong>To:</strong>
  <%= @message.to_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>