config/routes.rb
Rails.application.routes.draw do

  get '/:room_hash' => 'chats#room', :as => :chat

  get 'chats/room'

  get 'session/new'

  get 'session/create'

  resources :messages
  resources :dialogs

  root 'sessions#new'

  post '/login' => 'sessions#create', :as => :login

  get  '/chatroom/:room_hash' => 'chats#room', :as => :chat_old
  get  '/:room_hash/admin' => 'chats#admin', :as => :admin_room
  post  '/room_admin' => 'chats#update_room'
  post  '/change_name' => 'sessions#change_name', :as => :change_name
  get  '/my_rooms' => 'chats#index', :as => :chat_index

  get 'approve/:room_id/:user_id' => 'chats#approve', :as => :approve
  get 'get_out/:room_id/:user_id' => 'chats#get_out', :as => :get_out

end

app/models/chat.rb
class Chat < ActiveRecord::Base

  belongs_to :user, :foreign_key => :owner_id

  has_many :whitelists

  has_many :users, through: :whitelists
  has_many :messages, :foreign_key => :room_id

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def room
    chat = Chat.find_by_title(params[:room_hash])
    Rails.logger.info "-----|||||----> #{chat.id}"
    @chat = chat
    if session[:user_id]
      user = User.find(session[:user_id])
        if chat.user.id == session[:user_id] or (chat.whitelists.find_by_user_id(user.id) and chat.whitelists.find_by_user_id(user.id).approve)    #если пользователя пустили либо он создатель

          #приступаем к чату

        else  #если нет доступа

          if chat.users.include?(user)
              relation = chat.whitelists.find_by_user_id(user.id)
            else
              chat.users << user   #добавляем пользователя в чат
              relation = chat.whitelists.find_by_user_id(user.id)
              relation.approve = false                       #делаем его неподтвержденным в чате
              o = [('a'..'z'), ('A'..'Z')].map { |i| i.to_a }.flatten
              relation.salt = (0...7).map { o[rand(o.length)] }.join         #генерим соль


              # PrivatePub.publish_to("/add_user/#{chat.title}", "alert('к вам добавился #{relation.salt}')")

              PrivatePub.publish_to("/add_user/#{chat.title}/#{chat.owner_id}", "alert('к вам добавился #{relation.salt}'); location.reload();")



              Rails.logger.info "--------> #{relation.salt }"
              relation.save
          end
          @salt = relation.salt
          render 'get_salt'
          #рисуем соль
        end
    else

      user = User.create()
      session[:user_id] = user.id
      chat.users << user   #добавляем пользователя в чат
      relation = chat.whitelists.find_by_user_id(user.id)
      relation.approve = false                       #делаем его неподтвержденным в чате
      o = [('a'..'z'), ('A'..'Z')].map { |i| i.to_a }.flatten
      relation.salt = (0...7).map { o[rand(o.length)] }.join          #генерим соль

      PrivatePub.publish_to("/add_user/#{chat.title}/#{chat.owner_id}", "alert('к вам добавился #{relation.salt}'); location.reload();")





      relation.save
      @salt = relation.salt
      render 'get_salt'
      #генерим соль для доступа

    end




    # redirect_to '/login' unless session[:username]
    room = Chat.find_by_title(params[:room_hash])
    # @messages = Message.where(:room_id => room.id)
  end

  def index

  end

  def admin
     @chat = Chat.find_by_title(params[:room_hash])
  end

  def update_room
    chat = Chat.find_by_title(params[:some_data])
    @send = true
    @chat = chat
    params[:to_delete].each do |id|
      relation = chat.whitelists.find_by_user_id(id)
      relation.approve = false
      relation.save
      PrivatePub.publish_to("/approved_for_room/#{chat.title}/#{id.first}", "alert('Вас удалили из комнаты'); window.location.href = 'http://stackoverflow.com'")
    end unless params[:to_delete].nil?
    params[:to_accept].each do |id|
      relation = chat.whitelists.find_by_user_id(id)
      relation.approve = true
      relation.save
      PrivatePub.publish_to("/approved_for_room/#{chat.title}/#{id.first}", "alert('Вас добавили в комнату'); location.reload();")
    end unless params[:to_accept].nil?

    # PrivatePub.publish_to "/approved_for_room/#{chat.title}" do
    # "$('.site-wrapper').html('j render 'room', locals: {send: true}');"
    # end
    redirect_to :back
  end


  def approve
    chat = Chat.find(params[:room_id])
    relation = chat.whitelists.find_by_user_id(params[:user_id])
    relation.approve = true
    relation.save
    @send = true
    @chat = chat
  end

  def get_out
    chat = Chat.find(params[:room_id])
    relation = chat.whitelists.find_by_user_id(params[:user_id])
    relation.approve = false
    relation.save
  end

end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_room.erb
  <!--<form id="new_message_form">-->
  <!--<input type="text" id="message" name="message">-->
  <!--<input type="submit" value="Send">-->
  <!--</form>-->

  <% user_id = (@send)? params[:user_id] : session[:user_id] %>


  <div class="content">
    <div class="menu">
      <div class="link" style="font-size: 16px; font-weight: 100;"><a href="http://camewith.me/<%= @chat.title %>">camewith.me/<%= @chat.title %></a></div>
      <% if @chat.owner_id == user_id %>
          <%= link_to raw('<span class="glyphicon glyphicon-user"></span>участники'), admin_room_path, class: "btn btn-success"  %>
      <% else %>

      <% end %>
    </div>
    <% @chat.messages.each do |message| %>
        <div class="message" style="bottom: 0; ">
          <div class="name"><%= (message.user.username.blank?)? @chat.whitelists.find_by_user_id(message.user.id).salt : message.user.username %></div>
          <div class="text">
            <%= message.body %>
          </div>
        </div>
    <% end %>

    <%= form_for Message.new, remote: true, html: {:style => "position: fixed; bottom: 0; width: 100%; left: 0; background: #222; padding: 17px 20px;"} do |f| %>
        <%= hidden_field_tag :some_data, @chat.title %>
        <%= f.text_field :body, style: 'width: 100%;  padding: 7px; color: #333' %>
    <% end %>
    <%= subscribe_to "/messages/new/#{@chat.title}" %>
    <%= subscribe_to "/approved_for_room/#{@chat.title}/#{user_id}" %>
    <%= subscribe_to "/add_user/#{@chat.title}/#{@chat.owner_id}" %>
    <%# "/add_user/#{@chat.title}/#{@chat.owner_id}" %>

    <%# subscribe_to "/user_approve" %>
  </div>


  <style>

      div.content div.message:nth-child(2n+2) {
          background-color: rgba(95, 95, 95, 0.36);
      }
  </style>

app/views/chats/admin.html.erb
<%= subscribe_to "/add_user/#{@chat.title}/#{@chat.owner_id}" %>


<div class="admin">

  <%= link_to raw('<span class="glyphicon glyphicon-user"></span> перейти в комнату'), "/#{@chat.title}", class: "btn btn-success" %><div class="link" style="font-size: 20px; font-weight: 100;  margin-left: 20px;"><a href="http://camewith.me/<%= @chat.title %>">camewith.me/<%= @chat.title %></a></div>


  <%= form_tag '/change_name', method: :post do %>
      <div class="col-xs-6" style="padding-left: 0px;">
        <div class="input-group">
          <%= text_field_tag :username, session[:username], placeholder: 'ник в комнате', class: 'form-control' %>
                    <span class="input-group-btn">
                            <%= submit_tag 'ник', class: 'btn btn-default' %>

                    </span>
        </div>
      </div>
<% end %>

<%= form_tag '/room_admin', method: :post, :id => 'destroy_form' do %>
    <h2>В комнате</h2>

    <% @chat.users.each do |user| %>
        <% whitelist = @chat.whitelists.find_by_user_id(user.id) %>
        <% if whitelist.approve and user.id!=@chat.user.id %>
            <div class="user">
              <%= check_box_tag "[to_delete][#{user.id}]" %>
              <label><%= whitelist.salt %></label>
            </div>
        <% end %>
    <% end %>

    <%= hidden_field_tag 'some_data', @chat.title %>

    <%= submit_tag 'Удалить', class: 'btn btn-sm btn-danger' %>
    <!--<input type="submit" name="ban" value="Забанить" class="btn btn-sm btn-warning">-->
    <!--<input type="submit" name="kill" value="Удалить" class="btn btn-sm btn-danger">-->

  <% end %>
  <%= form_tag '/room_admin', method: :post, :id => 'accept_form' do %>

    <h2>Ожидают</h2>

    <% @chat.users.each do |user| %>
        <% whitelist = @chat.whitelists.find_by_user_id(user.id) %>
        <% unless whitelist.approve %>
            <div class="user">
              <%= check_box_tag "[to_accept][#{user.id}]" %>
              <label><%= whitelist.salt %></label>
            </div>
        <% end %>
    <% end %>

    <%= hidden_field_tag 'some_data', @chat.title %>
        <%= submit_tag 'Пригласить', class: 'btn btn-sm btn-success' %>


  <% end %>

</div>

app/views/chats/approve.js.erb
<% publish_to "/approved_for_room/#{@chat.title}" do %>
    $('.site-wrapper').html('<%= j render 'room', locals: {send: true} %>');
<% end %>

app/views/chats/get_salt.erb
<div class="site-wrapper empty">
  <div class="site-wrapper-inner">
    <div class="cover-container">

      <div class="masthead clearfix">
        <div class="inner">
          <h3 class="masthead-brand">cAmewith.me</h3>
          <ul class="nav masthead-nav">
            <li class="active"><a href="#">Глагне</a></li>
            <li><a href="#">FAQ</a></li>
            <li><a href="#">Contact</a></li>
          </ul>
        </div>
      </div>

      <div class="inner cover">
        <h1 class="cover-heading" style="margin-bottom: 50px; font-size: 4em; color: #5cb85c"><%= @salt %></h1>
        <p class="lead">
          Скопируй этот код и отдай создателю комнаты
        </p>
      </div>

      <div class="mastfoot">
        <div class="inner">
          <!--<p>Cover template for <a href="http://getbootstrap.com">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>-->
        </div>
      </div>
    </div>
  </div>
</div>

<%= subscribe_to "/approved_for_room/#{@chat.title}/#{session[:user_id]}" %>
<%= subscribe_to "/add_user" %>

app/views/chats/room.html.erb
<%= render 'room' %>