config/routes.rb
Rails.application.routes.draw do

  get '/:room_hash' => 'chats#room', :as => :chat

  get 'chats/room'

  get 'session/new'

  get 'session/create'

  resources :messages
  resources :dialogs

  root 'sessions#new'

  post '/login' => 'sessions#create', :as => :login

  get  '/chatroom/:room_hash' => 'chats#room', :as => :chat_old
  get  '/:room_hash/admin' => 'chats#admin', :as => :admin_room
  post  '/room_admin' => 'chats#update_room'
  post  '/change_name' => 'sessions#change_name', :as => :change_name
  get  '/my_rooms' => 'chats#index', :as => :chat_index

  get 'approve/:room_id/:user_id' => 'chats#approve', :as => :approve
  get 'get_out/:room_id/:user_id' => 'chats#get_out', :as => :get_out

end

app/models/dialog.rb
class Dialog < ActiveRecord::Base

  # belongs_to :user
  # belongs_to :participant, class_name: 'User', foreign_key: :participant_id

  def update_messages_count
    self.increment!(:messages_count)
  end

  def reset_messages_count
    self.update_attributes(messages_count: 0)
    Message.where(conversation_id: self.conversation_id, receiver_id: self.user_id).map { |m| m.update_attributes(read: true) }
  end

  def self.create_dialog(user_id, participant_id)
    dialog = Dialog.create(user_id: user_id, participant_id: participant_id)
    dialog.update(conversation_id: dialog.id)
    Dialog.create(user_id: participant_id, participant_id: user_id, conversation_id: dialog.id)
    return dialog
  end

  def messages
    Message.where(conversation_id: self.conversation_id, posted: true).order(:updated_at).reverse
  end

  def create_message
    message = Message.create_message(self)
  end

  def send_message(message_body)
    message = self.create_message
    message.update_attributes(sender_id: self.user_id, body: message_body, receiver_id: self.participant_id)
    message.update_dialogs if message.used?
    UserMailer.delay(run_at: 1.minutes.from_now).unread_message_notification(message)
    return message
  end

end

app/controllers/dialogs_controller.rb
class DialogsController < ApplicationController
  before_action :set_dialog, only: [:show, :edit, :update, :destroy]

  # GET /dialogs
  # GET /dialogs.json
  def index
    @dialogs = Dialog.all
  end

  # GET /dialogs/1
  # GET /dialogs/1.json
  def show
  end

  # GET /dialogs/new
  def new
    @dialog = Dialog.new
  end

  # GET /dialogs/1/edit
  def edit
  end

  # POST /dialogs
  # POST /dialogs.json
  def create
    @dialog = Dialog.new(dialog_params)

    respond_to do |format|
      if @dialog.save
        format.html { redirect_to @dialog, notice: 'Dialog was successfully created.' }
        format.json { render :show, status: :created, location: @dialog }
      else
        format.html { render :new }
        format.json { render json: @dialog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dialogs/1
  # PATCH/PUT /dialogs/1.json
  def update
    respond_to do |format|
      if @dialog.update(dialog_params)
        format.html { redirect_to @dialog, notice: 'Dialog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dialog }
      else
        format.html { render :edit }
        format.json { render json: @dialog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dialogs/1
  # DELETE /dialogs/1.json
  def destroy
    @dialog.destroy
    respond_to do |format|
      format.html { redirect_to dialogs_url, notice: 'Dialog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dialog
      @dialog = Dialog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dialog_params
      params[:dialog]
    end
end

app/helpers/dialogs_helper.rb
module DialogsHelper
end

app/views/dialogs/_form.html.erb
<%= form_for(@dialog) do |f| %>
  <% if @dialog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dialog.errors.count, "error") %> prohibited this dialog from being saved:</h2>

      <ul>
      <% @dialog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dialogs/edit.html.erb
<h1>Editing dialog</h1>

<%= render 'form' %>

<%= link_to 'Show', @dialog %> |
<%= link_to 'Back', dialogs_path %>

app/views/dialogs/index.html.erb
<h1>Listing dialogs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dialogs.each do |dialog| %>
      <tr>
        <td><%= link_to 'Show', dialog %></td>
        <td><%= link_to 'Edit', edit_dialog_path(dialog) %></td>
        <td><%= link_to 'Destroy', dialog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dialog', new_dialog_path %>

app/views/dialogs/new.html.erb
<h1>New dialog</h1>

<%= render 'form' %>

<%= link_to 'Back', dialogs_path %>

app/views/dialogs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_dialog_path(@dialog) %> |
<%= link_to 'Back', dialogs_path %>